name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Compile
        run: mvn -B clean package --file pom.xml
      - name: JAR包部署到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/MyBlogServe-1.0-SNAPSHOT.jar
          remote: MyBlogServe/jar/MyBlogServe-1.0-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: 在服务器启动
        uses: appleboy/ssh-action@master
        env:
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          BLOG_STATIC_FILES: ${{ secrets.BLOG_STATIC_FILES }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 20s
          envs: SERVER_PORT, BLOG_STATIC_FILES
          script: |
            cd MyBlogServe/jar/
            ps -ef | grep MyBlogServe-1.0-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9 
            nohup java -jar MyBlogServe-1.0-SNAPSHOT.jar --server.port="$SERVER_PORT" --spring.web.resources.static-locations="file:$BLOG_STATIC_FILES" > nohup.out &
            exit